language: scala
scala:
- 2.10.6
jdk:
- oraclejdk8
script:
- sbt clean test
deploy:
  provider: script
  script:
  - /bin/bash "$TRAVIS_BUILD_DIR/.travis.credentials.sh" && sbt publish
  on:
    tags: true
env:
  global:
  # travis encrypt BINTRAY_USER=xxx
  - secure: q1d/gzIaYaijJGfxOi6/xmJ+e11fGa2ki6zA9W8bvhKjUvN6M01AyikPSWUNYhC1KnS+wpmS+AOK5naN3nRhzaCY7r5xYRvs9mkiZCs/sZSdf1SjZM4TnETVnLoFJixjfF0YCSNUmaG35PCeB4+kt8o8ldtt3lOiHpfszV672N0f6lbPMBkfAG123d8aYy7cELWddMX5gRwXDmzccYUBRArAn3QP4Fh7WI96uNmCfhUbKXn2nUver2TU7jk3HNfEEbQ7zCzBAUDqqMZ5uU4nUqWjBiey+LhiFiuB0EMMXnW6xt4zdCUYegrSErCo2iFMMxJDoZuoGRHXSDjFNq7r590nJAqPNAGCuyJ3gNLZWMVWKWIZVdP1fDHVkxS7+GzLsnvI12YO6l6duKIV/3iPUf/XePjEIRfkfi2oyIjX+0Rougrf7lwa9SNeb/weQO+f2OG++nh4gSedQ2zknU2dbA+4W5JmGUG0iYyj1Pmsvf1XE62YUZdHh+CbCcAzw2OyMbEMLhxNBC6CAhq3eJ5PGpKP0tr5iXufcIRteOucQA+ruP4qnWrSGx2plIAEgMfdIHWvETxjFlVCotU4v7rlNv8HPkDXqibvNN9cW0uOPjSPuHODDvqb1Xz0EVqGIXepw5UIZ4PHNwJAUbBf8JanPqX7hrqc/GHCWq8T66i8nrY=
  # travis encrypt BINTRAY_PASSWORD=xxx
  - secure: lJT0PSjLfgp48xcnT1OMIwrnFspDLGqxSXspA9SvQU4FH9rqsuDMyorEWWA24L0PeosWMTsvkPEWh8q11RZRTYNEEHLXoO8dbIgqmdspinYcYy0GorwYVbiMbkC7d4VabwfSlgOwTnIn2AL+dTp9MZ0hhbPx2pf3F0SobVbypGtk+aEN8IynyvrKj7NOGBm8mH535oLTRR6PPqM75Uge4MFtb3GZ/Qo52TbQTTeVJvh0YV/S9JdJAmp3rDudZ+YbEpWwJu0umnoZQf4HVimhwlGCIn/di6kt/JMuhUw0znc77bjJIGe19ORxblPkb3wpvNvXGJhJ5ktpJhS/5WmAgRlfl3UdU/Yiv8p5Tb4+0vOhfITwiCOIIjGh5NTVzReu3UH7mmkYGa1T4hHoqh0R01U24aYxGmLJteq2vvDTtsAqgdFGkP3ELJDOjsBR1Hcl+IM8NJnZg/4L70iB4wvsKmNwBFSzFEnv7SeRptxWzZk9vMMrUoU5QAKpJhKu1wTzfuEzJWZM98HjQpbSiQ4ahfPfF5JNrZIr9MTdFsvTusqXCE9Uq4SLYAG3yH9c84Yq9FRFAtKfTz6CKVgLYCXFPS2nVgRjVmuHfAvJYEAuYc5Ii4s5g5b6HmFXbwKRFFIpESx4pH8AhLHp6xHlp/vkt2rlvDRRemaJs8tD9c6bB6w=
